export const BAILEYS_VERSION = '7.0.0-rc14';

export const BAILEYS_API_METHODS = [
  // Communities
  'communityMetadata',
  'communityCreate',
  'communityCreateGroup',
  'communityLeave',
  'communityUpdateSubject',
  'communityLinkGroup',
  'communityUnlinkGroup',
  'communityFetchLinkedGroups',
  'communityRequestParticipantsList',
  'communityRequestParticipantsUpdate',
  'communityParticipantsUpdate',
  'communityUpdateDescription',
  'communityInviteCode',
  'communityRevokeInvite',
  'communityAcceptInvite',
  'communityRevokeInviteV4',
  'communityAcceptInviteV4',
  'communityGetInviteInfo',
  'communityToggleEphemeral',
  'communitySettingUpdate',
  'communityMemberAddMode',
  'communityJoinApprovalMode',
  'communityFetchAllParticipating',

  // Business and catalog
  'getOrderDetails',
  'getCatalog',
  'getCollections',
  'productCreate',
  'productDelete',
  'productUpdate',
  'updateBussinesProfile',
  'updateCoverPhoto',
  'removeCoverPhoto',

  // Calls and messages
  'sendMessageAck',
  'sendRetryRequest',
  'rejectCall',
  'fetchMessageHistory',
  'requestPlaceholderResend',
  'issuePrivacyTokens',
  'relayMessage',
  'sendReceipt',
  'sendReceipts',
  'readMessages',
  'refreshMediaConn',
  'getMediaHost',
  'waUploadToServer',
  'fetchPrivacySettings',
  'sendPeerDataOperationMessage',
  'updateMemberLabel',
  'updateMediaMessage',
  'sendMessage',

  // Newsletters
  'newsletterCreate',
  'newsletterUpdate',
  'newsletterSubscribers',
  'newsletterMetadata',
  'newsletterFollow',
  'newsletterUnfollow',
  'newsletterMute',
  'newsletterUnmute',
  'newsletterUpdateName',
  'newsletterUpdateDescription',
  'newsletterUpdatePicture',
  'newsletterRemovePicture',
  'newsletterReactMessage',
  'newsletterFetchMessages',
  'subscribeNewsletterUpdates',
  'newsletterAdminCount',
  'newsletterChangeOwner',
  'newsletterDemote',
  'newsletterDelete',

  // Groups
  'groupMetadata',
  'groupCreate',
  'groupLeave',
  'groupUpdateSubject',
  'groupRequestParticipantsList',
  'groupRequestParticipantsUpdate',
  'groupParticipantsUpdate',
  'groupUpdateDescription',
  'groupInviteCode',
  'groupRevokeInvite',
  'groupAcceptInvite',
  'groupRevokeInviteV4',
  'groupAcceptInviteV4',
  'groupGetInviteInfo',
  'groupToggleEphemeral',
  'groupSettingUpdate',
  'groupMemberAddMode',
  'groupJoinApprovalMode',
  'groupFetchAllParticipating',

  // Account, profile, privacy, contacts and labels
  'createCallLink',
  'getBotListV2',
  'sendPresenceUpdate',
  'presenceSubscribe',
  'fetchBlocklist',
  'fetchStatus',
  'fetchDisappearingDuration',
  'updateProfilePicture',
  'removeProfilePicture',
  'updateProfileStatus',
  'updateProfileName',
  'updateBlockStatus',
  'updateDisableLinkPreviewsPrivacy',
  'updateCallPrivacy',
  'updateMessagesPrivacy',
  'updateLastSeenPrivacy',
  'updateOnlinePrivacy',
  'updateProfilePicturePrivacy',
  'updateStatusPrivacy',
  'updateReadReceiptsPrivacy',
  'updateGroupsAddPrivacy',
  'updateDefaultDisappearingMode',
  'getBusinessProfile',
  'resyncAppState',
  'chatModify',
  'cleanDirtyBits',
  'addOrEditContact',
  'removeContact',
  'addLabel',
  'addChatLabel',
  'removeChatLabel',
  'addMessageLabel',
  'removeMessageLabel',
  'star',
  'addOrEditQuickReply',
  'removeQuickReply',
  'fetchAccountReachoutTimelock',
  'fetchNewChatMessageCap',

  // Advanced protocol operations that accept JSON/binary arguments
  'appPatch',
  'query',
  'sendRawMessage',
  'uploadPreKeys',
  'uploadPreKeysToServerIfRequired',
  'digestKeyBundle',
  'rotateSignedPreKey',
  'requestPairingCode',
  'sendUnifiedSession',
  'sendWAMBuffer',
] as const;

export type BaileysApiMethod = (typeof BAILEYS_API_METHODS)[number];

export const BAILEYS_EXISTING_API_METHODS = [
  'onWhatsapp',
  'profilePictureUrl',
  'assertSessions',
  'createParticipantNodes',
  'getUSyncDevices',
  'generateMessageTag',
  'sendNode',
  'signalRepositoryDecryptMessage',
  'getAuthState',
] as const;

export const BAILEYS_UNSUPPORTED_API_METHODS = [
  'upsertMessage',
  'waUploadToServer',
  'waitForMessage',
  'waitForSocketOpen',
  'waitForConnectionUpdate',
  'registerSocketEndHandler',
  'onUnexpectedError',
  'executeUSyncQuery',
  'updateServerTimeOffset',
  'logout',
  'end',
] as const;

export function isBaileysApiMethod(value: string): value is BaileysApiMethod {
  return (BAILEYS_API_METHODS as readonly string[]).includes(value);
}
